// const { Client } = require('tplink-smarthome-api');
// let {PythonShell} = require('python-shell');



// const client = new Client();
// const plug = client.getDevice({host: '192.168.230.201'}).then((device)=>{
//   device.getSysInfo().then(console.log);
//   device.setPowerState(false);
// });



var myPythonScript = 'sample.py'

var {PythonShell} = require('python-shell');
var pyshell = new PythonShell(myPythonScript)
// do camera and firebase stuff
pyshell.on('message', function(message) {
    console.log(message);
        
});

pyshell.end(function(){
    console.log()
})


IncomingMessage {
    _readableState:
     ReadableState {
       objectMode: false,
       highWaterMark: 16384,
       buffer: BufferList { head: null, tail: null, length: 0 },
       length: 0,
       pipes: null,
       pipesCount: 0,
       flowing: null,
       ended: true,
       endEmitted: false,
       reading: false,
       sync: true,
       needReadable: false,
       emittedReadable: true,
       readableListening: false,
       resumeScheduled: false,
       destroyed: false,
       defaultEncoding: 'utf8',
       awaitDrain: 0,
       readingMore: true,
       decoder: null,
       encoding: null },
    readable: true,
    domain: null,
    _events: {},
    _eventsCount: 0,
    _maxListeners: undefined,
    socket:
     Socket {
       connecting: false,
       _hadError: false,
       _handle:
        TCP {
          reading: true,
          owner: [Circular],
          onread: [Function: onread],
          onconnection: null,
          writeQueueSize: 0,
          _consumed: true },
       _parent: null,
       _host: null,
       _readableState:
        ReadableState {
          objectMode: false,
          highWaterMark: 16384,
          buffer: [Object],
          length: 0,
          pipes: null,
          pipesCount: 0,
          flowing: true,
          ended: false,
          endEmitted: false,
          reading: true,
          sync: false,
          needReadable: true,
          emittedReadable: false,
          readableListening: false,
          resumeScheduled: false,
          destroyed: false,
          defaultEncoding: 'utf8',
          awaitDrain: 0,
          readingMore: false,
          decoder: null,
          encoding: null },
       readable: true,
       domain: null,
       _events:
        { end: [Array],
          _socketEnd: [Function: onSocketEnd],
          drain: [Array],
          timeout: [Function: socketOnTimeout],
          data: [Function: bound socketOnData],
          error: [Array],
          close: [Array],
          resume: [Function: onSocketResume],
          pause: [Function: onSocketPause] },
       _eventsCount: 9,
       _maxListeners: undefined,
       _writableState:
        WritableState {
          objectMode: false,
          highWaterMark: 16384,
          finalCalled: false,
          needDrain: false,
          ending: false,
          ended: false,
          finished: false,
          destroyed: false,
          decodeStrings: false,
          defaultEncoding: 'utf8',
          length: 0,
          writing: false,
          corked: 0,
          sync: true,
          bufferProcessing: false,
          onwrite: [Function: bound onwrite],
          writecb: null,
          writelen: 0,
          bufferedRequest: null,
          lastBufferedRequest: null,
          pendingcb: 0,
          prefinished: false,
          errorEmitted: false,
          bufferedRequestCount: 0,
          corkedRequestsFree: [Object] },
       writable: true,
       allowHalfOpen: true,
       _bytesDispatched: 0,
       _sockname: null,
       _pendingData: null,
       _pendingEncoding: '',
       server:
        Server {
          domain: null,
          _events: [Object],
          _eventsCount: 2,
          _maxListeners: undefined,
          _connections: 1,
          _handle: [Object],
          _usingSlaves: false,
          _slaves: [],
          _unref: false,
          allowHalfOpen: true,
          pauseOnConnect: false,
          httpAllowHalfOpen: false,
          timeout: 120000,
          keepAliveTimeout: 5000,
          _pendingResponseData: 0,
          maxHeadersCount: null,
          headersTimeout: 40000,
          _connectionKey: '6::::4445',
          [Symbol(IncomingMessage)]: [Object],
          [Symbol(ServerResponse)]: [Object],
          [Symbol(asyncId)]: 12 },
       _server:
        Server {
          domain: null,
          _events: [Object],
          _eventsCount: 2,
          _maxListeners: undefined,
          _connections: 1,
          _handle: [Object],
          _usingSlaves: false,
          _slaves: [],
          _unref: false,
          allowHalfOpen: true,
          pauseOnConnect: false,
          httpAllowHalfOpen: false,
          timeout: 120000,
          keepAliveTimeout: 5000,
          _pendingResponseData: 0,
          maxHeadersCount: null,
          headersTimeout: 40000,
          _connectionKey: '6::::4445',
          [Symbol(IncomingMessage)]: [Object],
          [Symbol(ServerResponse)]: [Object],
          [Symbol(asyncId)]: 12 },
       _idleTimeout: 120000,
       _idleNext:
        TimersList {
          _idleNext: [Circular],
          _idlePrev: [Circular],
          _timer: [Object],
          _unrefed: true,
          msecs: 120000,
          nextTick: false },
       _idlePrev:
        TimersList {
          _idleNext: [Circular],
          _idlePrev: [Circular],
          _timer: [Object],
          _unrefed: true,
          msecs: 120000,
          nextTick: false },
       _idleStart: 14975,
       _destroyed: false,
       parser:
        HTTPParser {
          '0': [Function: parserOnHeaders],
          '1': [Function: parserOnHeadersComplete],
          '2': [Function: parserOnBody],
          '3': [Function: parserOnMessageComplete],
          '4': [Function: bound onParserExecute],
          _headers: [],
          _url: '',
          _consumed: true,
          socket: [Circular],
          incoming: [Circular],
          outgoing: null,
          maxHeaderPairs: 2000,
          onIncoming: [Function: bound parserOnIncoming],
          parsingHeadersStart: 0,
          [Symbol(isReused)]: true },
       on: [Function: socketOnWrap],
       _paused: false,
       _httpMessage:
        ServerResponse {
          domain: null,
          _events: [Object],
          _eventsCount: 2,
          _maxListeners: undefined,
          output: [],
          outputEncodings: [],
          outputCallbacks: [],
          outputSize: 0,
          writable: true,
          _last: false,
          upgrading: false,
          chunkedEncoding: false,
          shouldKeepAlive: true,
          useChunkedEncodingByDefault: true,
          sendDate: true,
          _removedConnection: false,
          _removedContLen: false,
          _removedTE: false,
          _contentLength: null,
          _hasBody: true,
          _trailer: '',
          finished: false,
          _headerSent: false,
          socket: [Circular],
          connection: [Circular],
          _header: null,
          _onPendingData: [Function: bound updateOutgoingData],
          _sent100: false,
          _expect_continue: false,
          req: [Circular],
          locals: {},
          _startAt: undefined,
          _startTime: undefined,
          writeHead: [Function: writeHead],
          __onFinished: [Object],
          [Symbol(outHeadersKey)]: [Object] },
       _peername: { address: '::1', family: 'IPv6', port: 53876 },
       [Symbol(asyncId)]: 852,
       [Symbol(bytesRead)]: 0,
       [Symbol(asyncId)]: 853,
       [Symbol(triggerAsyncId)]: 852 },
    connection:
     Socket {
       connecting: false,
       _hadError: false,
       _handle:
        TCP {
          reading: true,
          owner: [Circular],
          onread: [Function: onread],
          onconnection: null,
          writeQueueSize: 0,
          _consumed: true },
       _parent: null,
       _host: null,
       _readableState:
        ReadableState {
          objectMode: false,
          highWaterMark: 16384,
          buffer: [Object],
          length: 0,
          pipes: null,
          pipesCount: 0,
          flowing: true,
          ended: false,
          endEmitted: false,
          reading: true,
          sync: false,
          needReadable: true,
          emittedReadable: false,
          readableListening: false,
          resumeScheduled: false,
          destroyed: false,
          defaultEncoding: 'utf8',
          awaitDrain: 0,
          readingMore: false,
          decoder: null,
          encoding: null },
       readable: true,
       domain: null,
       _events:
        { end: [Array],
          _socketEnd: [Function: onSocketEnd],
          drain: [Array],
          timeout: [Function: socketOnTimeout],
          data: [Function: bound socketOnData],
          error: [Array],
          close: [Array],
          resume: [Function: onSocketResume],
          pause: [Function: onSocketPause] },
       _eventsCount: 9,
       _maxListeners: undefined,
       _writableState:
        WritableState {
          objectMode: false,
          highWaterMark: 16384,
          finalCalled: false,
          needDrain: false,
          ending: false,
          ended: false,
          finished: false,
          destroyed: false,
          decodeStrings: false,
          defaultEncoding: 'utf8',
          length: 0,
          writing: false,
          corked: 0,
          sync: true,
          bufferProcessing: false,
          onwrite: [Function: bound onwrite],
          writecb: null,
          writelen: 0,
          bufferedRequest: null,
          lastBufferedRequest: null,
          pendingcb: 0,
          prefinished: false,
          errorEmitted: false,
          bufferedRequestCount: 0,
          corkedRequestsFree: [Object] },
       writable: true,
       allowHalfOpen: true,
       _bytesDispatched: 0,
       _sockname: null,
       _pendingData: null,
       _pendingEncoding: '',
       server:
        Server {
          domain: null,
          _events: [Object],
          _eventsCount: 2,
          _maxListeners: undefined,
          _connections: 1,
          _handle: [Object],
          _usingSlaves: false,
          _slaves: [],
          _unref: false,
          allowHalfOpen: true,
          pauseOnConnect: false,
          httpAllowHalfOpen: false,
          timeout: 120000,
          keepAliveTimeout: 5000,
          _pendingResponseData: 0,
          maxHeadersCount: null,
          headersTimeout: 40000,
          _connectionKey: '6::::4445',
          [Symbol(IncomingMessage)]: [Object],
          [Symbol(ServerResponse)]: [Object],
          [Symbol(asyncId)]: 12 },
       _server:
        Server {
          domain: null,
          _events: [Object],
          _eventsCount: 2,
          _maxListeners: undefined,
          _connections: 1,
          _handle: [Object],
          _usingSlaves: false,
          _slaves: [],
          _unref: false,
          allowHalfOpen: true,
          pauseOnConnect: false,
          httpAllowHalfOpen: false,
          timeout: 120000,
          keepAliveTimeout: 5000,
          _pendingResponseData: 0,
          maxHeadersCount: null,
          headersTimeout: 40000,
          _connectionKey: '6::::4445',
          [Symbol(IncomingMessage)]: [Object],
          [Symbol(ServerResponse)]: [Object],
          [Symbol(asyncId)]: 12 },
       _idleTimeout: 120000,
       _idleNext:
        TimersList {
          _idleNext: [Circular],
          _idlePrev: [Circular],
          _timer: [Object],
          _unrefed: true,
          msecs: 120000,
          nextTick: false },
       _idlePrev:
        TimersList {
          _idleNext: [Circular],
          _idlePrev: [Circular],
          _timer: [Object],
          _unrefed: true,
          msecs: 120000,
          nextTick: false },
       _idleStart: 14975,
       _destroyed: false,
       parser:
        HTTPParser {
          '0': [Function: parserOnHeaders],
          '1': [Function: parserOnHeadersComplete],
          '2': [Function: parserOnBody],
          '3': [Function: parserOnMessageComplete],
          '4': [Function: bound onParserExecute],
          _headers: [],
          _url: '',
          _consumed: true,
          socket: [Circular],
          incoming: [Circular],
          outgoing: null,
          maxHeaderPairs: 2000,
          onIncoming: [Function: bound parserOnIncoming],
          parsingHeadersStart: 0,
          [Symbol(isReused)]: true },
       on: [Function: socketOnWrap],
       _paused: false,
       _httpMessage:
        ServerResponse {
          domain: null,
          _events: [Object],
          _eventsCount: 2,
          _maxListeners: undefined,
          output: [],
          outputEncodings: [],
          outputCallbacks: [],
          outputSize: 0,
          writable: true,
          _last: false,
          upgrading: false,
          chunkedEncoding: false,
          shouldKeepAlive: true,
          useChunkedEncodingByDefault: true,
          sendDate: true,
          _removedConnection: false,
          _removedContLen: false,
          _removedTE: false,
          _contentLength: null,
          _hasBody: true,
          _trailer: '',
          finished: false,
          _headerSent: false,
          socket: [Circular],
          connection: [Circular],
          _header: null,
          _onPendingData: [Function: bound updateOutgoingData],
          _sent100: false,
          _expect_continue: false,
          req: [Circular],
          locals: {},
          _startAt: undefined,
          _startTime: undefined,
          writeHead: [Function: writeHead],
          __onFinished: [Object],
          [Symbol(outHeadersKey)]: [Object] },
       _peername: { address: '::1', family: 'IPv6', port: 53876 },
       [Symbol(asyncId)]: 852,
       [Symbol(bytesRead)]: 0,
       [Symbol(asyncId)]: 853,
       [Symbol(triggerAsyncId)]: 852 },
    httpVersionMajor: 1,
    httpVersionMinor: 1,
    httpVersion: '1.1',
    complete: true,
    headers:
     { 'content-type': 'application/json',
       'cache-control': 'no-cache',
       'postman-token': 'a0bf7289-e4b3-4990-b7f1-64850d6bcc68',
       'user-agent': 'PostmanRuntime/7.2.0',
       accept: '*/*',
       host: 'localhost:4445',
       cookie: 'connect.sid=s%3Afc34V8NAFfe_54lOxLLd1JWxmAA5Sney.hB2QQYqD6i4jfdX7Q2hQziF%2FKWKSBup7a8tnzv1pXAU',
       'accept-encoding': 'gzip, deflate',
       connection: 'keep-alive' },
    rawHeaders:
     [ 'Content-Type',
       'application/json',
       'cache-control',
       'no-cache',
       'Postman-Token',
       'a0bf7289-e4b3-4990-b7f1-64850d6bcc68',
       'User-Agent',
       'PostmanRuntime/7.2.0',
       'Accept',
       '*/*',
       'Host',
       'localhost:4445',
       'cookie',
       'connect.sid=s%3Afc34V8NAFfe_54lOxLLd1JWxmAA5Sney.hB2QQYqD6i4jfdX7Q2hQziF%2FKWKSBup7a8tnzv1pXAU',
       'accept-encoding',
       'gzip, deflate',
       'Connection',
       'keep-alive' ],
    trailers: {},
    rawTrailers: [],
    aborted: false,
    upgrade: false,
    url: '/hsapi?plugStatus=true',
    method: 'GET',
    statusCode: null,
    statusMessage: null,
    client:
     Socket {
       connecting: false,
       _hadError: false,
       _handle:
        TCP {
          reading: true,
          owner: [Circular],
          onread: [Function: onread],
          onconnection: null,
          writeQueueSize: 0,
          _consumed: true },
       _parent: null,
       _host: null,
       _readableState:
        ReadableState {
          objectMode: false,
          highWaterMark: 16384,
          buffer: [Object],
          length: 0,
          pipes: null,
          pipesCount: 0,
          flowing: true,
          ended: false,
          endEmitted: false,
          reading: true,
          sync: false,
          needReadable: true,
          emittedReadable: false,
          readableListening: false,
          resumeScheduled: false,
          destroyed: false,
          defaultEncoding: 'utf8',
          awaitDrain: 0,
          readingMore: false,
          decoder: null,
          encoding: null },
       readable: true,
       domain: null,
       _events:
        { end: [Array],
          _socketEnd: [Function: onSocketEnd],
          drain: [Array],
          timeout: [Function: socketOnTimeout],
          data: [Function: bound socketOnData],
          error: [Array],
          close: [Array],
          resume: [Function: onSocketResume],
          pause: [Function: onSocketPause] },
       _eventsCount: 9,
       _maxListeners: undefined,
       _writableState:
        WritableState {
          objectMode: false,
          highWaterMark: 16384,
          finalCalled: false,
          needDrain: false,
          ending: false,
          ended: false,
          finished: false,
          destroyed: false,
          decodeStrings: false,
          defaultEncoding: 'utf8',
          length: 0,
          writing: false,
          corked: 0,
          sync: true,
          bufferProcessing: false,
          onwrite: [Function: bound onwrite],
          writecb: null,
          writelen: 0,
          bufferedRequest: null,
          lastBufferedRequest: null,
          pendingcb: 0,
          prefinished: false,
          errorEmitted: false,
          bufferedRequestCount: 0,
          corkedRequestsFree: [Object] },
       writable: true,
       allowHalfOpen: true,
       _bytesDispatched: 0,
       _sockname: null,
       _pendingData: null,
       _pendingEncoding: '',
       server:
        Server {
          domain: null,
          _events: [Object],
          _eventsCount: 2,
          _maxListeners: undefined,
          _connections: 1,
          _handle: [Object],
          _usingSlaves: false,
          _slaves: [],
          _unref: false,
          allowHalfOpen: true,
          pauseOnConnect: false,
          httpAllowHalfOpen: false,
          timeout: 120000,
          keepAliveTimeout: 5000,
          _pendingResponseData: 0,
          maxHeadersCount: null,
          headersTimeout: 40000,
          _connectionKey: '6::::4445',
          [Symbol(IncomingMessage)]: [Object],
          [Symbol(ServerResponse)]: [Object],
          [Symbol(asyncId)]: 12 },
       _server:
        Server {
          domain: null,
          _events: [Object],
          _eventsCount: 2,
          _maxListeners: undefined,
          _connections: 1,
          _handle: [Object],
          _usingSlaves: false,
          _slaves: [],
          _unref: false,
          allowHalfOpen: true,
          pauseOnConnect: false,
          httpAllowHalfOpen: false,
          timeout: 120000,
          keepAliveTimeout: 5000,
          _pendingResponseData: 0,
          maxHeadersCount: null,
          headersTimeout: 40000,
          _connectionKey: '6::::4445',
          [Symbol(IncomingMessage)]: [Object],
          [Symbol(ServerResponse)]: [Object],
          [Symbol(asyncId)]: 12 },
       _idleTimeout: 120000,
       _idleNext:
        TimersList {
          _idleNext: [Circular],
          _idlePrev: [Circular],
          _timer: [Object],
          _unrefed: true,
          msecs: 120000,
          nextTick: false },
       _idlePrev:
        TimersList {
          _idleNext: [Circular],
          _idlePrev: [Circular],
          _timer: [Object],
          _unrefed: true,
          msecs: 120000,
          nextTick: false },
       _idleStart: 14975,
       _destroyed: false,
       parser:
        HTTPParser {
          '0': [Function: parserOnHeaders],
          '1': [Function: parserOnHeadersComplete],
          '2': [Function: parserOnBody],
          '3': [Function: parserOnMessageComplete],
          '4': [Function: bound onParserExecute],
          _headers: [],
          _url: '',
          _consumed: true,
          socket: [Circular],
          incoming: [Circular],
          outgoing: null,
          maxHeaderPairs: 2000,
          onIncoming: [Function: bound parserOnIncoming],
          parsingHeadersStart: 0,
          [Symbol(isReused)]: true },
       on: [Function: socketOnWrap],
       _paused: false,
       _httpMessage:
        ServerResponse {
          domain: null,
          _events: [Object],
          _eventsCount: 2,
          _maxListeners: undefined,
          output: [],
          outputEncodings: [],
          outputCallbacks: [],
          outputSize: 0,
          writable: true,
          _last: false,
          upgrading: false,
          chunkedEncoding: false,
          shouldKeepAlive: true,
          useChunkedEncodingByDefault: true,
          sendDate: true,
          _removedConnection: false,
          _removedContLen: false,
          _removedTE: false,
          _contentLength: null,
          _hasBody: true,
          _trailer: '',
          finished: false,
          _headerSent: false,
          socket: [Circular],
          connection: [Circular],
          _header: null,
          _onPendingData: [Function: bound updateOutgoingData],
          _sent100: false,
          _expect_continue: false,
          req: [Circular],
          locals: {},
          _startAt: undefined,
          _startTime: undefined,
          writeHead: [Function: writeHead],
          __onFinished: [Object],
          [Symbol(outHeadersKey)]: [Object] },
       _peername: { address: '::1', family: 'IPv6', port: 53876 },
       [Symbol(asyncId)]: 852,
       [Symbol(bytesRead)]: 0,
       [Symbol(asyncId)]: 853,
       [Symbol(triggerAsyncId)]: 852 },
    _consuming: false,
    _dumped: false,
    next: [Function: next],
    baseUrl: '',
    originalUrl: '/hsapi?plugStatus=true',
    _parsedUrl:
     Url {
       protocol: null,
       slashes: null,
       auth: null,
       host: null,
       port: null,
       hostname: null,
       hash: null,
       search: '?plugStatus=true',
       query: 'plugStatus=true',
       pathname: '/hsapi',
       path: '/hsapi?plugStatus=true',
       href: '/hsapi?plugStatus=true',
       _raw: '/hsapi?plugStatus=true' },
    params: {},
    query: { plugStatus: 'true' },
    res:
     ServerResponse {
       domain: null,
       _events: { finish: [Array], end: [Function: onevent] },
       _eventsCount: 2,
       _maxListeners: undefined,
       output: [],
       outputEncodings: [],
       outputCallbacks: [],
       outputSize: 0,
       writable: true,
       _last: false,
       upgrading: false,
       chunkedEncoding: false,
       shouldKeepAlive: true,
       useChunkedEncodingByDefault: true,
       sendDate: true,
       _removedConnection: false,
       _removedContLen: false,
       _removedTE: false,
       _contentLength: null,
       _hasBody: true,
       _trailer: '',
       finished: false,
       _headerSent: false,
       socket:
        Socket {
          connecting: false,
          _hadError: false,
          _handle: [Object],
          _parent: null,
          _host: null,
          _readableState: [Object],
          readable: true,
          domain: null,
          _events: [Object],
          _eventsCount: 9,
          _maxListeners: undefined,
          _writableState: [Object],
          writable: true,
          allowHalfOpen: true,
          _bytesDispatched: 0,
          _sockname: null,
          _pendingData: null,
          _pendingEncoding: '',
          server: [Object],
          _server: [Object],
          _idleTimeout: 120000,
          _idleNext: [Object],
          _idlePrev: [Object],
          _idleStart: 14975,
          _destroyed: false,
          parser: [Object],
          on: [Function: socketOnWrap],
          _paused: false,
          _httpMessage: [Circular],
          _peername: [Object],
          [Symbol(asyncId)]: 852,
          [Symbol(bytesRead)]: 0,
          [Symbol(asyncId)]: 853,
          [Symbol(triggerAsyncId)]: 852 },
       connection:
        Socket {
          connecting: false,
          _hadError: false,
          _handle: [Object],
          _parent: null,
          _host: null,
          _readableState: [Object],
          readable: true,
          domain: null,
          _events: [Object],
          _eventsCount: 9,
          _maxListeners: undefined,
          _writableState: [Object],
          writable: true,
          allowHalfOpen: true,
          _bytesDispatched: 0,
          _sockname: null,
          _pendingData: null,
          _pendingEncoding: '',
          server: [Object],
          _server: [Object],
          _idleTimeout: 120000,
          _idleNext: [Object],
          _idlePrev: [Object],
          _idleStart: 14975,
          _destroyed: false,
          parser: [Object],
          on: [Function: socketOnWrap],
          _paused: false,
          _httpMessage: [Circular],
          _peername: [Object],
          [Symbol(asyncId)]: 852,
          [Symbol(bytesRead)]: 0,
          [Symbol(asyncId)]: 853,
          [Symbol(triggerAsyncId)]: 852 },
       _header: null,
       _onPendingData: [Function: bound updateOutgoingData],
       _sent100: false,
       _expect_continue: false,
       req: [Circular],
       locals: {},
       _startAt: undefined,
       _startTime: undefined,
       writeHead: [Function: writeHead],
       __onFinished: { [Function: listener] queue: [Array] },
       [Symbol(outHeadersKey)]:
        { 'x-powered-by': [Array],
          'access-control-allow-origin': [Array] } },
    _startAt: [ 17870, 957906136 ],
    _startTime: 2018-12-26T19:32:15.621Z,
    _remoteAddress: '::1',
    body: {},
    secret: undefined,
    cookies:
     { 'connect.sid': 's:fc34V8NAFfe_54lOxLLd1JWxmAA5Sney.hB2QQYqD6i4jfdX7Q2hQziF/KWKSBup7a8tnzv1pXAU' },
    signedCookies: {},
    _parsedOriginalUrl:
     Url {
       protocol: null,
       slashes: null,
       auth: null,
       host: null,
       port: null,
       hostname: null,
       hash: null,
       search: '?plugStatus=true',
       query: 'plugStatus=true',
       pathname: '/hsapi',
       path: '/hsapi?plugStatus=true',
       href: '/hsapi?plugStatus=true',
       _raw: '/hsapi?plugStatus=true' },
    route: Route { path: '/hsapi', stack: [ [Object] ], methods: { get: true } } } 'Status defined'
  ^C:smart_home_pi$ BBBB